Drive bug
ipsaone/ANNA-Frontend pull request #40
Opened 2019-12-01 14:12 UTC by M1nlex

Fixing the drive page bug with "this.selectedFile"

2019-12-01 17:25 UTC, MagixInTheAir commented
Too many changes, please sync your branch

2019-12-14 10:35 UTC, pwnorbitals requested changes
Fix branch synchronization

2020-03-18 19:23 UTC, MagixInTheAir commented
Any news ?

2020-04-09 19:22 UTC, pwnorbitals approved these changes

2020-04-09 19:49 UTC, merged